### ISSUE TITLE
Is tileMatrixSetURI really optional?

### ISSUE THREAD

**Issue by tschaub** [opengeospatial/2D-Tile-Matrix-Set#3]
The [current schema](https://github.com/opengeospatial/OGC-API-Tiles/blob/2a8f9e351034a14535de119808370cc467065a66/core/standard/requirements/tiles/core/REQ_sct-tmxslink.adoc) for a `tileMatrixSetLink-entry` looks like this:

```yml
  tileMatrixSetLink-entry:
    type: object
    required:
      - tileMatrixSet
    properties:
      tileMatrixSet:
        type: string
        example: 'WebMercatorQuad'
      tileMatrixSetURI:
        type: string
        format: uri
        example: 'http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad'
```

Is it intentional that the `tileMatrixSetURI` property is optional?  If so, it isn't clear to me how a client is supposed to generate the [`tileMatrix`](https://github.com/opengeospatial/OGC-API-Tiles/blob/5335da20ca44f9a81982e3d7dfc5aaaa7843928b/core/standard/requirements/tiles/root/REQ_tcs-tilematrix-definition.adoc) for a tile request.
